version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "----- Installing system dependencies -----"
      - apt-get update
      - apt-get install -y unzip curl wget xvfb
      - echo "Installing Google Chrome..."
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt install -y ./google-chrome-stable_current_amd64.deb
      - echo "Installing ChromeDriver..."
      - CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
      - wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
      - wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
      - echo "Verifying if chromedriver.zip exists..."
      - ls -lh chromedriver.zip
      - echo "Unzipping chromedriver..."
      - unzip -o chromedriver.zip -d /usr/bin/
      - chmod +x /usr/bin/chromedriver
      - echo "Chrome and ChromeDriver installed successfully"
      - echo "Installing Allure CLI"
      - wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.27.0/allure-commandline-2.27.0.zip -O allure.zip
      - unzip allure.zip -d /opt/
      - export PATH=$PATH:/opt/allure-2.27.0/bin
      - allure --version
      - echo "----- Installing Python dependencies -----"
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest pytest-html selenium
  pre_build:
    commands:
      - echo "----- Checking versions -----"
      - google-chrome --version
      - chromedriver --version
      - python --version
      - pytest --version

  build:
    commands:
      - echo "Running Pytest with Allure"
      - mkdir -p allure-results
      - pytest --alluredir=allure-results --disable-warnings -v
      - echo "-----Generating Allure HTML report-----"
      - allure generate allure-results -o allure-report --clean



  post_build:
    commands:
      - echo "Uploading Allure report to S3..."
      - aws s3 cp allure-report s3://test-bucket-selenium-pytest/allure-report/ --recursive
      - echo "Allure report uploaded successfully!"


artifacts:
  files:
    - reports/report.html
  discard-paths: yes
