version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "----- Installing system dependencies -----"
      - apt-get update
      - apt-get install -y unzip curl wget xvfb
      - echo "Installing Google Chrome..."
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt install -y ./google-chrome-stable_current_amd64.deb
      - echo "Installing ChromeDriver..."
      - CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
      - wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
      - wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
      - echo "Verifying if chromedriver.zip exists..."
      - ls -lh chromedriver.zip
      - echo "Unzipping chromedriver..."
      - unzip -o chromedriver.zip -d /usr/bin/
      - chmod +x /usr/bin/chromedriver
      - echo "Chrome and ChromeDriver installed successfully"
      - echo "----- Installing Python dependencies -----"
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest pytest-html selenium
  pre_build:
    commands:
      - echo "----- Checking versions -----"
      - google-chrome --version
      - chromedriver --version
      - python --version
      - pytest --version

  build:
    commands:
      - echo "----- Starting Selenium + Pytest tests -----"
      - mkdir -p reports
      - pytest --html=reports/report.html --self-contained-html --maxfail=1 --disable-warnings
      - echo "Tests execution completed!"

  post_build:
    commands:
      - echo "----- Post-build actions -----"
      - ls -la reports/
      - echo "Build completed on $(date)"

artifacts:
  files:
    - reports/report.html
  discard-paths: yes
